/**
 *
 * $Id$
 */
package resources.validation;

import environment.LinkingResource;

import resources.resourcetype.CommunicationLinkResourceType;

/**
 * A sample validator interface for {@link resources.CommunicationLinkResourceSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommunicationLinkResourceSpecificationValidator {
	boolean validate();

	boolean validateLinkingResource_CommunicationLinkResourceSpecification(LinkingResource value);
	boolean validateCommunicationLinkResourceType_CommunicationLinkResourceSpecification(CommunicationLinkResourceType value);
}
