/**
 *
 * $Id$
 */
package resources.validation;

import resources.ResourceContainer;

import resources.resourcetype.ProcessingResourceType;
import resources.resourcetype.SchedulingPolicy;

/**
 * A sample validator interface for {@link resources.ProcessingResourceSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessingResourceSpecificationValidator {
	boolean validate();

	boolean validateRequiredByContainer(boolean value);
	boolean validateSchedulingPolicy(SchedulingPolicy value);
	boolean validateActiveResourceType_ActiveResourceSpecification(ProcessingResourceType value);
	boolean validateNumberOfReplicas(int value);
	boolean validateResourceContainer_ProcessingResourceSpecification(ResourceContainer value);
}
