/**
 *
 * $Id$
 */
package resources.validation;

import environment.Container;

import org.eclipse.emf.common.util.EList;

import resources.HDDProcessingResourceSpecification;
import resources.ProcessingResourceSpecification;

/**
 * A sample validator interface for {@link resources.ResourceContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceContainerValidator {
	boolean validate();

	boolean validateContainer(Container value);
	boolean validateActiveResourceSpecifications_ResourceContainer(EList<ProcessingResourceSpecification> value);
	boolean validateHddResourceSpecifications(EList<HDDProcessingResourceSpecification> value);
}
