/**
 *
 * $Id$
 */
package resources.resourcetype.validation;

import org.eclipse.emf.common.util.EList;

import resources.resourcetype.ResourceType;
import resources.resourcetype.SchedulingPolicy;

/**
 * A sample validator interface for {@link resources.resourcetype.ResourceRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceRepositoryValidator {
	boolean validate();

	boolean validateSchedulingPolicies__ResourceRepository(EList<SchedulingPolicy> value);
	boolean validateAvailableResourceTypes_ResourceRepository(EList<ResourceType> value);
}
