/**
 *
 * $Id$
 */
package resources.resourcetype.validation;

import resources.resourcetype.ResourceRepository;

/**
 * A sample validator interface for {@link resources.resourcetype.SchedulingPolicy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SchedulingPolicyValidator {
	boolean validate();

	boolean validateResourceRepository__SchedulingPolicy(ResourceRepository value);
}
